### PR TITLE
Add cursive italics

### LINKED ISSUE #3: Add italics
See #2 , and please accept it. Thank you!

### PR DESCRIPTION
**Pull request by cssobral2013**
This PR wishes to add italics to Caskaydia Cove, in particular, the Cursive version, and close #3.

### CODE REVIEW

**Comment by eliheuer** [comment]
Thank you! Sorry, I didn't see this sooner, will review it soon. :-)

**Comment by M1ndo** [comment]
@cssobral2013 Add valid source build files, i couldn't build them.

**Comment by cssobral2013** [comment]
@M1ndo - The build.sh has been updated to include the newly added Italic.

**Comment by eliheuer** [comment]
This repo is unmaintained so I'm closing this, sorry!

**Comment by greed-d** [comment]
> This PR wishes to add italics to Caskaydia Cove, in particular, the Cursive version, and close #3.

Can you please make an italic to non cursive version for [this](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode)? @cssobral2013

**Comment by M1ndo** [comment]
> > This PR wishes to add italics to Caskaydia Cove, in particular, the Cursive version, and close #3.
> 
> Can you please make an italic to non cursive version for [this](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode)? @cssobral2013

I'm pretty sure the repo is unmaintained and no longer will be updated, but you could copy the source files and make non cursive version yourself.

**Pull request closed without merging**
